package tk.mybatis.simple.model;

public class Country {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.id
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.countryname
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	private String countryname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column country.countrycode
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	private String countrycode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.id
	 * @return  the value of country.id
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.id
	 * @param id  the value for country.id
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.countryname
	 * @return  the value of country.countryname
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public String getCountryname() {
		return countryname;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.countryname
	 * @param countryname  the value for country.countryname
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public void setCountryname(String countryname) {
		this.countryname = countryname == null ? null : countryname.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column country.countrycode
	 * @return  the value of country.countrycode
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public String getCountrycode() {
		return countrycode;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column country.countrycode
	 * @param countrycode  the value for country.countrycode
	 * @mbggenerated  Sat Jun 30 15:52:36 CST 2018
	 */
	public void setCountrycode(String countrycode) {
		this.countrycode = countrycode == null ? null : countrycode.trim();
	}
	/*private Long id;
	private String countryname;
	private String countrycode;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getCountryname() {
		return countryname;
	}
	public void setCountryname(String countryname) {
		this.countryname = countryname;
	}
	public String getCountrycode() {
		return countrycode;
	}
	public void setCountrycode(String countrycode) {
		this.countrycode = countrycode;
	}*/
}
